INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(1, 1, 0, 0);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(2, 1, 1, 1);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(3, 1, 1, 2);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(4, 2, 0, 0);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(5, 2, 1, 1);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(6, 2, 1, 2);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(7, 3, 0, 0);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(8, 3, 1, 1);
INSERT INTO ClausePoints(clause_id, note_id, imp, und) VALUES(9, 3, 1, 2);