INSERT INTO ClausePoints(clause_id, imp, und) VALUES(1, 0, 0);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(2, 1, 1);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(3, 1, 2);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(4, 0, 0);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(5, 1, 1);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(6, 1, 2);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(7, 0, 0);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(8, 1, 1);
INSERT INTO ClausePoints(clause_id, imp, und) VALUES(9, 1, 2);